name = "robog-net-portfolio"
compatibility_date = "2024-01-01"

[env.production.build]
command = "npx @11ty/eleventy"
cwd = ""

[env.production]
account_id = ""
route = ""

[[env.production.routes]]
pattern = "*"
custom_domain = true